import type { Listing, RentDataPoint } from './types';

// Realistic sample listings scattered across Mumbai neighbourhoods so the app
// has something to render in demo mode (i.e. without a Supabase connection).
// Coordinates are approximate centroids of popular rental pockets.

const now = new Date().toISOString();

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'mock-1',
    user_id: null,
    kind: 'flat',
    title: '1BHK near Bandra station, sea-facing balcony',
    description: '5 min walk to Bandra station (west). Fully furnished, piped gas, 24x7 water.',
    rent: 52000,
    deposit: 150000,
    bhk_type: '1BHK',
    furnishing: 'furnished',
    area_name: 'Bandra West',
    lat: 19.055,
    lng: 72.8296,
    images: [],
    tags: ['bachelor_friendly', 'pet_friendly'],
    contact_whatsapp: '919999900001',
    created_at: now,
  },
  {
    id: 'mock-2',
    user_id: null,
    kind: 'flat',
    title: 'Cozy 2BHK in Powai near Hiranandani',
    description: 'Walkable to tech parks. Semi-furnished, parking, gym in society.',
    rent: 65000,
    deposit: 195000,
    bhk_type: '2BHK',
    furnishing: 'semi',
    area_name: 'Powai',
    lat: 19.1197,
    lng: 72.9051,
    images: [],
    tags: ['family_preferred'],
    contact_whatsapp: '919999900002',
    created_at: now,
  },
  {
    id: 'mock-3',
    user_id: null,
    kind: 'flatmate',
    title: 'Flatmate needed — shared room in Andheri East',
    description: 'Metro 2 min. Working professional, non-smoker. Split utilities.',
    rent: 18000,
    deposit: 36000,
    bhk_type: 'Shared',
    furnishing: 'furnished',
    area_name: 'Andheri East',
    lat: 19.1197,
    lng: 72.8468,
    images: [],
    tags: ['bachelor_friendly', 'vegetarian_only'],
    contact_whatsapp: '919999900003',
    created_at: now,
  },
  {
    id: 'mock-4',
    user_id: null,
    kind: 'flat',
    title: '1RK in Dadar, steps from station',
    description: 'Compact 1RK, ideal for single working professional.',
    rent: 28000,
    deposit: 84000,
    bhk_type: '1RK',
    furnishing: 'semi',
    area_name: 'Dadar West',
    lat: 19.0176,
    lng: 72.8562,
    images: [],
    tags: ['bachelor_friendly'],
    contact_whatsapp: '919999900004',
    created_at: now,
  },
  {
    id: 'mock-5',
    user_id: null,
    kind: 'flat',
    title: '3BHK in Juhu near beach',
    description: 'Spacious, family home, fully furnished with appliances.',
    rent: 130000,
    deposit: 390000,
    bhk_type: '3BHK',
    furnishing: 'furnished',
    area_name: 'Juhu',
    lat: 19.0883,
    lng: 72.8264,
    images: [],
    tags: ['family_preferred', 'pet_friendly'],
    contact_whatsapp: '919999900005',
    created_at: now,
  },
  {
    id: 'mock-6',
    user_id: null,
    kind: 'flat',
    title: '2BHK Thane West, lake view',
    description: 'Brand new tower, club house, parking. Close to Ghodbunder Rd.',
    rent: 42000,
    deposit: 126000,
    bhk_type: '2BHK',
    furnishing: 'semi',
    area_name: 'Thane West',
    lat: 19.2183,
    lng: 72.9781,
    images: [],
    tags: ['family_preferred'],
    contact_whatsapp: '919999900006',
    created_at: now,
  },
  {
    id: 'mock-7',
    user_id: null,
    kind: 'room',
    title: 'Private room in Malad West PG',
    description: 'Working women PG, meals included, WiFi, AC.',
    rent: 16000,
    deposit: 32000,
    bhk_type: 'Room',
    furnishing: 'furnished',
    area_name: 'Malad West',
    lat: 19.1869,
    lng: 72.8484,
    images: [],
    tags: ['women_only'],
    contact_whatsapp: '919999900007',
    created_at: now,
  },
  {
    id: 'mock-8',
    user_id: null,
    kind: 'flat',
    title: '1BHK in Lower Parel, business-district',
    description: 'Walk to Phoenix, Kamala Mills. Fully furnished tower apartment.',
    rent: 75000,
    deposit: 225000,
    bhk_type: '1BHK',
    furnishing: 'furnished',
    area_name: 'Lower Parel',
    lat: 18.9967,
    lng: 72.8305,
    images: [],
    tags: ['bachelor_friendly'],
    contact_whatsapp: '919999900008',
    created_at: now,
  },
  {
    id: 'mock-9',
    user_id: null,
    kind: 'flat',
    title: '2BHK Goregaon East near Metro',
    description: 'Close to Nesco, Oberoi Mall. Family building.',
    rent: 48000,
    deposit: 144000,
    bhk_type: '2BHK',
    furnishing: 'semi',
    area_name: 'Goregaon East',
    lat: 19.1550,
    lng: 72.8499,
    images: [],
    tags: ['family_preferred'],
    contact_whatsapp: '919999900009',
    created_at: now,
  },
  {
    id: 'mock-10',
    user_id: null,
    kind: 'flat',
    title: '1BHK in Chembur near Monorail',
    description: 'Great connectivity, near Diamond Garden. Semi-furnished.',
    rent: 32000,
    deposit: 96000,
    bhk_type: '1BHK',
    furnishing: 'semi',
    area_name: 'Chembur',
    lat: 19.0632,
    lng: 72.9001,
    images: [],
    tags: ['family_preferred'],
    contact_whatsapp: '919999900010',
    created_at: now,
  },
  {
    id: 'mock-11',
    user_id: null,
    kind: 'flat',
    title: '2BHK Vikhroli East, IIT-B commute',
    description: 'Close to Godrej IT park. Good metro & bus access.',
    rent: 45000,
    deposit: 135000,
    bhk_type: '2BHK',
    furnishing: 'semi',
    area_name: 'Vikhroli East',
    lat: 19.1070,
    lng: 72.9268,
    images: [],
    tags: [],
    contact_whatsapp: '919999900011',
    created_at: now,
  },
  {
    id: 'mock-12',
    user_id: null,
    kind: 'flat',
    title: '1BHK Ghatkopar West, near metro',
    description: 'Well maintained building, close to R-City Mall.',
    rent: 36000,
    deposit: 108000,
    bhk_type: '1BHK',
    furnishing: 'semi',
    area_name: 'Ghatkopar West',
    lat: 19.0866,
    lng: 72.9081,
    images: [],
    tags: ['family_preferred'],
    contact_whatsapp: '919999900012',
    created_at: now,
  },
];

// Additional rent data points (pure sightings, not full listings) so the rent
// insight tool has more samples to work with in demo mode.
export const MOCK_RENT_POINTS: RentDataPoint[] = [
  { id: 'rp-1', lat: 19.0596, lng: 72.8295, rent: 58000, bhk_type: '1BHK', area_name: 'Bandra West', notes: null, created_at: now },
  { id: 'rp-2', lat: 19.0702, lng: 72.8310, rent: 95000, bhk_type: '2BHK', area_name: 'Bandra West', notes: null, created_at: now },
  { id: 'rp-3', lat: 19.1189, lng: 72.9060, rent: 70000, bhk_type: '2BHK', area_name: 'Powai', notes: null, created_at: now },
  { id: 'rp-4', lat: 19.1150, lng: 72.8471, rent: 35000, bhk_type: '1BHK', area_name: 'Andheri East', notes: null, created_at: now },
  { id: 'rp-5', lat: 19.1247, lng: 72.8365, rent: 52000, bhk_type: '2BHK', area_name: 'Andheri West', notes: null, created_at: now },
  { id: 'rp-6', lat: 19.0176, lng: 72.8562, rent: 30000, bhk_type: '1RK', area_name: 'Dadar', notes: null, created_at: now },
  { id: 'rp-7', lat: 18.9967, lng: 72.8305, rent: 82000, bhk_type: '1BHK', area_name: 'Lower Parel', notes: null, created_at: now },
  { id: 'rp-8', lat: 19.2183, lng: 72.9781, rent: 40000, bhk_type: '2BHK', area_name: 'Thane West', notes: null, created_at: now },
  { id: 'rp-9', lat: 19.1869, lng: 72.8484, rent: 38000, bhk_type: '2BHK', area_name: 'Malad West', notes: null, created_at: now },
  { id: 'rp-10', lat: 19.0632, lng: 72.9001, rent: 33000, bhk_type: '1BHK', area_name: 'Chembur', notes: null, created_at: now },
  { id: 'rp-11', lat: 19.0883, lng: 72.8264, rent: 140000, bhk_type: '3BHK', area_name: 'Juhu', notes: null, created_at: now },
  { id: 'rp-12', lat: 19.1550, lng: 72.8499, rent: 50000, bhk_type: '2BHK', area_name: 'Goregaon East', notes: null, created_at: now },
];
